services:
  ai_rest_backend:
    build: .
    container_name: ai_rest_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/ai_rest_backend/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    working_dir: /usr/src/ai_rest_backend
    depends_on:
      - db
  
  db:
    image: mysql:8.3
    container_name: ai_restaurant_db
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: ai_restaurant
      MYSQL_USER: ai_restaurant
      MYSQL_PASSWORD: ai_restaurant
    ports:
      - "3306:3306"

volumes:
  mysql_data:
