name: Django CI/CD

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    name: Run Django Tests
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.3]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set environment for CI
        run: echo "GITHUB_ACTIONS=true" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Migrations
        run: |
          python manage.py migrate --noinput

      - name: Run Tests
        run: |
          python manage.py test

  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest
    needs: build  # ✅ build(Job)이 성공해야 실행됨
    if: github.ref == 'refs/heads/main'  # ✅ main 브랜치에만 배포

    steps:
      - name: SSH & Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.DIR }}
            git pull origin main
            docker compose down
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d --build
            docker compose -f docker-compose.prod.yml exec web python manage.py migrate --noinput
            docker compose -f docker-compose.prod.yml exec web python manage.py collectstatic --noinput
